name: Configure pyenv and pick the right version wip
on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
 # python installtion
  install-python:
  # should run on linux based operating system
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Set up python 3.7
          uses: actions/setup-python@v2
          with:
              python-version: 3.7
        - name: Install dependencies
          run:
              python -m pip install --upgrade pip
              pip install -r requirements.txt
        - name: Run Unit Tests and generate coverage report
          run: |
            cd test
            python -m unittest test_simple.TSDTest
            coverage run -m unittest
            coverage report
            coverage html